print("Hello")
print('salman khan')
print(7)
print(7.7)
print(True)
print('Hello',1,4.5,True)
print('Hello',1,4.5,True,sep='/') 
print('Hello',1,4.5,True,sep='&') 
print('hello')
print('world')
print('hello',end='-')
print('world')